# Generated by Django 5.2.17 on 2026-10-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0012_ficha_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatisticas',
            name='carisma',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ficha',
            name='tamanho',
            field=models.CharField(default='Médio', max_length=16),
        ),
        migrations.AddField(
            model_name='pericia',
            name='atributo',
            field=models.CharField(choices=[('FOR', 'FOR'), ('DES', 'DES'), ('CON', 'CON'), ('INT', 'INT'), ('SAB', 'SAB'), ('CAR', 'CAR')], default='FOR', max_length=3),
        ),
    ]
