# Generated by Django 5.2.17 on 2026-09-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0010_alter_ficha_foto_personagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatisticas',
            name='pe_atual',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='pe_maximos',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='pv_atual',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='pv_maximos',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='sanidade_atual',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='sanidade_maxima',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
