# Generated by Django 5.2.17 on 2026-10-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0011_alter_estatisticas_pe_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='sistema',
            field=models.CharField(choices=[('ordem_paranormal', 'Ordem Paranormal'), ('tormenta20', 'Tormenta 20')], default='ordem_paranormal', max_length=32),
        ),
    ]
